var p = new Position()

console.log("X goes...")
p.addToX(4)
console.log("O goes...")
p.addToO(0)
console.log("X goes...")
p.addToX(2)
console.log("O goes...")
p.addToO(3)
console.log("X goes...")
p.addToX(6)
console.log(p.getPositionStatus())
console.log(p)
console.log("DONE!!")
