import React, { Component } from 'react';

class App extends Component {

    // In contrast with other tools that also help with DOM manipulation, such 
    // as Angular, React embraces the concept of one-way data flow. This means 
    // that when using React, the view is generated by React, but does not 
    // communicate directly back to it. Instead, actions generated by your views 
    // such as clicks and key presses must go through an intermediate layer which 
    // React calls the dispatcher. This dispatcher decides how to interpret the 
    // action and what changes, if any, should be made to your application state. 
    // React documentation refers to the state of your application as the store.
    render() {
        return (
            <div>
                <h1>Hello, World!</h1>
            </div>
        )
    }
}

export default App;